services:
  - type: web
    name: esp32-openweather-dashboard
    runtime: node
    rootDir: dashboard
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MQTT_URL
        value: mqtt://broker.hivemq.com:1883
      - key: BOARD_ID
        value: esp32-weather-001
      - key: MQTT_BASE_TOPIC
        value: esp32/weather
      - key: DASHBOARD_PIN
        sync: false
