#pragma once

#define BOARD_ID_VALUE "esp32-weather-smartyyy-8f42"
#define OPENWEATHER_API_KEY_VALUE "PUT_YOUR_OPENWEATHER_API_KEY_HERE"
#define TELEGRAM_BOT_TOKEN_VALUE "PUT_YOUR_TELEGRAM_BOT_TOKEN_HERE"
#define TELEGRAM_CHAT_ID_VALUE "PUT_YOUR_TELEGRAM_CHAT_ID_HERE"
